[phases.setup]
# uses bun 1.0.18
nixpkgsArchive = '9c69bc8cae2f3b38536a50801961e2e62da13595'

[build]
cmd = "bun build --target=bun --compile --minify-whitespace --minify-syntax --target bun --outfile server ./src/index.ts"

[start]
cmd = "bun run server"